# Generated by Django 3.0.8 on 2020-07-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0002_auto_20200711_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlistitem',
            name='watched',
            field=models.BooleanField(null=True),
        ),
    ]
